In [7]:
import numpy as np

size = 3
A = np.arange(0, size)
B = np.arange(1, size+1)

print(A[:, None])
print()
print(B[None, :])
print()
print(A[:, None] * B[None, :] + 1)

[[0]
 [1]
 [2]]

[[1 2 3]]

[[1 1 1]
 [2 3 4]
 [3 5 7]]


In [14]:
import torch

tensor1 = torch.Tensor([
    [1, 2, 3, 4],
    [0, 2, 3, 4],
    [0, 0, 3, 4],
    [0, 0, 0, 4]
])

print(tensor1.diagonal())

tensor([1., 2., 3., 4.])


In [4]:
import torch

def init_array_fixed(n: int) -> torch.Tensor:
    A = torch.zeros((n, n), dtype=torch.float64)
    for i in range(n):
        for j in range(i):
            A[i, j] = (-j % n) / n + 1
            A[j, i] = A[i, j]
        A[i, i] = n*2
        
    return A

print(init_array_fixed(5))

tensor([[10.0000,  1.0000,  1.0000,  1.0000,  1.0000],
        [ 1.0000, 10.0000,  1.8000,  1.8000,  1.8000],
        [ 1.0000,  1.8000, 10.0000,  1.6000,  1.6000],
        [ 1.0000,  1.8000,  1.6000, 10.0000,  1.4000],
        [ 1.0000,  1.8000,  1.6000,  1.4000, 10.0000]], dtype=torch.float64)


In [3]:
import torch

def init_array_fixed(n: int) -> torch.Tensor:
    A = torch.zeros((n, n), dtype=torch.float64)
    for i in range(n):
        for j in range(i):
            A[i, j] = (-j % n) / n + 1
            A[j, i] = A[i, j]
        A[i, i] = 2
        
    return A

print(init_array_fixed(6))

tensor([[2.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 2.0000, 1.8333, 1.8333, 1.8333, 1.8333],
        [1.0000, 1.8333, 2.0000, 1.6667, 1.6667, 1.6667],
        [1.0000, 1.8333, 1.6667, 2.0000, 1.5000, 1.5000],
        [1.0000, 1.8333, 1.6667, 1.5000, 2.0000, 1.3333],
        [1.0000, 1.8333, 1.6667, 1.5000, 1.3333, 2.0000]], dtype=torch.float64)


In [3]:
import torch

t1 = torch.Tensor([1.0, 1.8])
t2 = torch.Tensor([[1., 0.], [1., 1.]])

print(torch.mv(t2, t1))

tensor([1.0000, 2.8000])


In [16]:
import torch

tens1 = torch.arange(1, 26).reshape(5, 5).float()
tens1[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4]] = 0
print(tens1)
print(torch.nn.functional.conv2d(
    input=tens1.unsqueeze(0).unsqueeze(0),
    weight=torch.tensor([[[[0, 0.2, 0], [0.2, 0.2, 0.2], [0, 0.2, 0]]]])
)[0,0])

tensor([[ 0.,  2.,  3.,  4.,  5.],
        [ 6.,  0.,  8.,  9., 10.],
        [11., 12.,  0., 14., 15.],
        [16., 17., 18.,  0., 20.],
        [21., 22., 23., 24.,  0.]])
tensor([[ 5.6000,  4.0000,  9.0000],
        [ 8.0000, 10.4000,  7.6000],
        [17.0000, 11.6000, 15.2000]])


In [2]:
import torch

tensor1 = torch.Tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(tensor1.copy_())

TypeError: copy_() received an invalid combination of arguments - got (), but expected (Tensor other, bool non_blocking)

In [4]:
tup1 = (1, 2)
tup2 = (1, 3)

print(tup1 == tup2)

False


In [3]:
import torch
import torch.nn.functional as F

t1 = torch.Tensor([
    [1, 1, 1],
    [1, 6, 1],
    [1, 1, 1]
])

print(F.conv2d(
    t1.unsqueeze(0).unsqueeze(0), 
    torch.Tensor([[[[0.0, 0.2, 0.0], [0.2, 0.2, 0.2], [0.0, 0.2, 0.0]]]])).squeeze())

tensor(2.0000)


In [1]:
import torch

def kernel_conv_3d(A):
    # Define the convolution kernel
    kernel = torch.tensor([
        [[2, 4, 5, 7, -8, 10, -3, 6, -9, 2, 4, 5, 7, -8, 10]]
    ], dtype=A.dtype)

    # Perform the convolution using PyTorch's F.conv3d function
    B = torch.nn.functional.conv3d(A.unsqueeze(0), kernel.unsqueeze(0)).squeeze()

    return B

# Example usage:
if __name__ == "__main__":
    # Create a sample 3D tensor (4x4x4) for illustration
    A = torch.tensor([
        [[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]],

        [[17, 18, 19, 20],
         [21, 22, 23, 24],
         [25, 26, 27, 28],
         [29, 30, 31, 32]],

        [[33, 34, 35, 36],
         [37, 38, 39, 40],
         [41, 42, 43, 44],
         [45, 46, 47, 48]],

        [[49, 50, 51, 52],
         [53, 54, 55, 56],
         [57, 58, 59, 60],
         [61, 62, 63, 64]],
    ], dtype=torch.float32)

    # Perform the 3D convolution
    result = kernel_conv_3d(A)

    print("Input 3D tensor (A):")
    print(A)

    print("\nOutput 3D tensor (B):")
    print(result)


RuntimeError: expected stride to be a single integer value or a list of 2 values to match the convolution dimensions, but got stride=[1, 1, 1]